// Generated by gencpp from file yolo/number.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_NUMBER_H
#define YOLO_MESSAGE_NUMBER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo
{
template <class ContainerAllocator>
struct number_
{
  typedef number_<ContainerAllocator> Type;

  number_()
    : number(0)
    , MaxH(0.0)
    , MinH(0.0)
    , CenterH(0.0)
    , AverageH(0.0)
    , x(0)
    , y(0)  {
    }
  number_(const ContainerAllocator& _alloc)
    : number(0)
    , MaxH(0.0)
    , MinH(0.0)
    , CenterH(0.0)
    , AverageH(0.0)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint8_t _number_type;
  _number_type number;

   typedef float _MaxH_type;
  _MaxH_type MaxH;

   typedef float _MinH_type;
  _MinH_type MinH;

   typedef float _CenterH_type;
  _CenterH_type CenterH;

   typedef float _AverageH_type;
  _AverageH_type AverageH;

   typedef uint8_t _x_type;
  _x_type x;

   typedef uint8_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::yolo::number_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo::number_<ContainerAllocator> const> ConstPtr;

}; // struct number_

typedef ::yolo::number_<std::allocator<void> > number;

typedef boost::shared_ptr< ::yolo::number > numberPtr;
typedef boost::shared_ptr< ::yolo::number const> numberConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo::number_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo::number_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo::number_<ContainerAllocator1> & lhs, const ::yolo::number_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.MaxH == rhs.MaxH &&
    lhs.MinH == rhs.MinH &&
    lhs.CenterH == rhs.CenterH &&
    lhs.AverageH == rhs.AverageH &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo::number_<ContainerAllocator1> & lhs, const ::yolo::number_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo::number_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo::number_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::number_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::number_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::number_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::number_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8414b5a969236b037efc4bd669e714c5";
  }

  static const char* value(const ::yolo::number_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8414b5a969236b03ULL;
  static const uint64_t static_value2 = 0x7efc4bd669e714c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo/number";
  }

  static const char* value(const ::yolo::number_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 number\n"
"float32 MaxH\n"
"float32 MinH\n"
"float32 CenterH\n"
"float32 AverageH\n"
"uint8 x\n"
"uint8 y\n"
;
  }

  static const char* value(const ::yolo::number_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo::number_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.MaxH);
      stream.next(m.MinH);
      stream.next(m.CenterH);
      stream.next(m.AverageH);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct number_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo::number_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo::number_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "MaxH: ";
    Printer<float>::stream(s, indent + "  ", v.MaxH);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "MinH: ";
    Printer<float>::stream(s, indent + "  ", v.MinH);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CenterH: ";
    Printer<float>::stream(s, indent + "  ", v.CenterH);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "AverageH: ";
    Printer<float>::stream(s, indent + "  ", v.AverageH);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_NUMBER_H
