// Generated by gencpp from file yolo/yolo.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_YOLO_H
#define YOLO_MESSAGE_YOLO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo
{
template <class ContainerAllocator>
struct yolo_
{
  typedef yolo_<ContainerAllocator> Type;

  yolo_()
    : leixing()
    , x(0)
    , y(0)
    , confidence(0.0)  {
    }
  yolo_(const ContainerAllocator& _alloc)
    : leixing(_alloc)
    , x(0)
    , y(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _leixing_type;
  _leixing_type leixing;

   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::yolo::yolo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo::yolo_<ContainerAllocator> const> ConstPtr;

}; // struct yolo_

typedef ::yolo::yolo_<std::allocator<void> > yolo;

typedef boost::shared_ptr< ::yolo::yolo > yoloPtr;
typedef boost::shared_ptr< ::yolo::yolo const> yoloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo::yolo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo::yolo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo::yolo_<ContainerAllocator1> & lhs, const ::yolo::yolo_<ContainerAllocator2> & rhs)
{
  return lhs.leixing == rhs.leixing &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo::yolo_<ContainerAllocator1> & lhs, const ::yolo::yolo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo::yolo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo::yolo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::yolo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::yolo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::yolo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::yolo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo::yolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1740de2716a9dc4b45746fc186bca2f5";
  }

  static const char* value(const ::yolo::yolo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1740de2716a9dc4bULL;
  static const uint64_t static_value2 = 0x45746fc186bca2f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo::yolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo/yolo";
  }

  static const char* value(const ::yolo::yolo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo::yolo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string leixing\n"
"uint16 x\n"
"uint16 y\n"
"float32 confidence\n"
"\n"
;
  }

  static const char* value(const ::yolo::yolo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo::yolo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leixing);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo::yolo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo::yolo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "leixing: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.leixing);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_YOLO_H
