// Generated by gencpp from file unencoder/decode.msg
// DO NOT EDIT!


#ifndef UNENCODER_MESSAGE_DECODE_H
#define UNENCODER_MESSAGE_DECODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unencoder
{
template <class ContainerAllocator>
struct decode_
{
  typedef decode_<ContainerAllocator> Type;

  decode_()
    : data(0)
    , is_valid(false)  {
    }
  decode_(const ContainerAllocator& _alloc)
    : data(0)
    , is_valid(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;





  typedef boost::shared_ptr< ::unencoder::decode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unencoder::decode_<ContainerAllocator> const> ConstPtr;

}; // struct decode_

typedef ::unencoder::decode_<std::allocator<void> > decode;

typedef boost::shared_ptr< ::unencoder::decode > decodePtr;
typedef boost::shared_ptr< ::unencoder::decode const> decodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unencoder::decode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unencoder::decode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unencoder::decode_<ContainerAllocator1> & lhs, const ::unencoder::decode_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.is_valid == rhs.is_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unencoder::decode_<ContainerAllocator1> & lhs, const ::unencoder::decode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unencoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unencoder::decode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unencoder::decode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unencoder::decode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unencoder::decode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unencoder::decode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unencoder::decode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unencoder::decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7470f513ee83a01fc610ee9182c0f80";
  }

  static const char* value(const ::unencoder::decode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7470f513ee83a01ULL;
  static const uint64_t static_value2 = 0xfc610ee9182c0f80ULL;
};

template<class ContainerAllocator>
struct DataType< ::unencoder::decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unencoder/decode";
  }

  static const char* value(const ::unencoder::decode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unencoder::decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data\n"
"bool  is_valid\n"
;
  }

  static const char* value(const ::unencoder::decode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unencoder::decode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct decode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unencoder::decode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unencoder::decode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNENCODER_MESSAGE_DECODE_H
