// Generated by gencpp from file bluesea2/ControlResponse.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_CONTROLRESPONSE_H
#define BLUESEA2_MESSAGE_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluesea2
{
template <class ContainerAllocator>
struct ControlResponse_
{
  typedef ControlResponse_<ContainerAllocator> Type;

  ControlResponse_()
    : code(0)
    , value()  {
    }
  ControlResponse_(const ContainerAllocator& _alloc)
    : code(0)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::bluesea2::ControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluesea2::ControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlResponse_

typedef ::bluesea2::ControlResponse_<std::allocator<void> > ControlResponse;

typedef boost::shared_ptr< ::bluesea2::ControlResponse > ControlResponsePtr;
typedef boost::shared_ptr< ::bluesea2::ControlResponse const> ControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluesea2::ControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluesea2::ControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluesea2::ControlResponse_<ContainerAllocator1> & lhs, const ::bluesea2::ControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluesea2::ControlResponse_<ContainerAllocator1> & lhs, const ::bluesea2::ControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluesea2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluesea2::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2048e343f4bc3eabab899a87af89e425";
  }

  static const char* value(const ::bluesea2::ControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2048e343f4bc3eabULL;
  static const uint64_t static_value2 = 0xab899a87af89e425ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluesea2::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluesea2/ControlResponse";
  }

  static const char* value(const ::bluesea2::ControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluesea2::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   code\n"
"string value\n"
;
  }

  static const char* value(const ::bluesea2::ControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluesea2::ControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluesea2::ControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluesea2::ControlResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUESEA2_MESSAGE_CONTROLRESPONSE_H
