// Generated by gencpp from file bluesea2/ControlRequest.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_CONTROLREQUEST_H
#define BLUESEA2_MESSAGE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluesea2
{
template <class ContainerAllocator>
struct ControlRequest_
{
  typedef ControlRequest_<ContainerAllocator> Type;

  ControlRequest_()
    : topic()
    , func()
    , flag(0)
    , params()  {
    }
  ControlRequest_(const ContainerAllocator& _alloc)
    : topic(_alloc)
    , func(_alloc)
    , flag(0)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _topic_type;
  _topic_type topic;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _func_type;
  _func_type func;

   typedef int8_t _flag_type;
  _flag_type flag;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::bluesea2::ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluesea2::ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRequest_

typedef ::bluesea2::ControlRequest_<std::allocator<void> > ControlRequest;

typedef boost::shared_ptr< ::bluesea2::ControlRequest > ControlRequestPtr;
typedef boost::shared_ptr< ::bluesea2::ControlRequest const> ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluesea2::ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluesea2::ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluesea2::ControlRequest_<ContainerAllocator1> & lhs, const ::bluesea2::ControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.topic == rhs.topic &&
    lhs.func == rhs.func &&
    lhs.flag == rhs.flag &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluesea2::ControlRequest_<ContainerAllocator1> & lhs, const ::bluesea2::ControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluesea2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "812e328e972e98d18e9abb089b71000e";
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x812e328e972e98d1ULL;
  static const uint64_t static_value2 = 0x8e9abb089b71000eULL;
};

template<class ContainerAllocator>
struct DataType< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluesea2/ControlRequest";
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string topic\n"
"string func\n"
"int8   flag\n"
"string params\n"
;
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluesea2::ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topic);
      stream.next(m.func);
      stream.next(m.flag);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluesea2::ControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.topic);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "func: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.func);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "params: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUESEA2_MESSAGE_CONTROLREQUEST_H
