# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yolo/number.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class number(genpy.Message):
  _md5sum = "8414b5a969236b037efc4bd669e714c5"
  _type = "yolo/number"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 number
float32 MaxH
float32 MinH
float32 CenterH
float32 AverageH
uint8 x
uint8 y
"""
  __slots__ = ['number','MaxH','MinH','CenterH','AverageH','x','y']
  _slot_types = ['uint8','float32','float32','float32','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       number,MaxH,MinH,CenterH,AverageH,x,y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(number, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.number is None:
        self.number = 0
      if self.MaxH is None:
        self.MaxH = 0.
      if self.MinH is None:
        self.MinH = 0.
      if self.CenterH is None:
        self.CenterH = 0.
      if self.AverageH is None:
        self.AverageH = 0.
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
    else:
      self.number = 0
      self.MaxH = 0.
      self.MinH = 0.
      self.CenterH = 0.
      self.AverageH = 0.
      self.x = 0
      self.y = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4f2B().pack(_x.number, _x.MaxH, _x.MinH, _x.CenterH, _x.AverageH, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.number, _x.MaxH, _x.MinH, _x.CenterH, _x.AverageH, _x.x, _x.y,) = _get_struct_B4f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4f2B().pack(_x.number, _x.MaxH, _x.MinH, _x.CenterH, _x.AverageH, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.number, _x.MaxH, _x.MinH, _x.CenterH, _x.AverageH, _x.x, _x.y,) = _get_struct_B4f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4f2B = None
def _get_struct_B4f2B():
    global _struct_B4f2B
    if _struct_B4f2B is None:
        _struct_B4f2B = struct.Struct("<B4f2B")
    return _struct_B4f2B
